# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
      # Or, if you're on Windows: echo "Build number is ${env:BUILD_NUMBER}"
    - name: Checkout Project B
      uses: actions/checkout@master
      with: 
        repository: VkasSharma/repob
        token: ${{ secrets.ACTIONS_TOKEN }}
        path: ./repob
    - name: change image tag in values.yml file
      run: |
        FILE=./repoa/file
        sed 'N avikas sharma' ./repoa/file
    - name: Change tag in helm chart
      run: |
        cd ./repob
        git add .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "Image tag modify after pushing to harbor"
        git push
