#test
name: deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: harbor.metabob.com
          username: admin
          password: Harbor12345
      - name: Build Docker Image with latest Build Number
        run: |
          docker pull nginx
          docker tag nginx:latest harbor.metabob.com/k8s/node:latest
          docker push harbor.metabob.com/k8s/node:latest
        
